In [139]:
import pandas as pd
pd

In [171]:
all_source_data = pd.read_csv(filepath_or_buffer='fw.source',delimiter='\t',index_col=False)
all_series_data = pd.read_csv(filepath_or_buffer='fw.series',delimiter='\t',index_col=False)
all_seasonal_data = pd.read_csv(filepath_or_buffer='fw.seasonal',delimiter='\t',index_col=False)
all_occupation_data = pd.read_csv(filepath_or_buffer='fw.occupation',delimiter='\t',index_col=False)
all_industry_data = pd.read_csv(filepath_or_buffer='fw.industry',delimiter='\t',index_col=False)
all_event_data = pd.read_csv(filepath_or_buffer='fw.event',delimiter='\t',index_col=False)
all_data = pd.read_csv(filepath_or_buffer='fw.data.1.AllData',delimiter='\t',index_col=False)
all_contacts_data = pd.read_csv(filepath_or_buffer='fw.contacts',delimiter='\t',index_col=False)
all_category2_data = pd.read_csv(filepath_or_buffer='fw.category2',delimiter='\t',index_col=False)
all_category_data = pd.read_csv(filepath_or_buffer='fw.category',delimiter='\t',index_col=False)
all_case_data = pd.read_csv(filepath_or_buffer='fw.case',delimiter='\t',index_col=False)
all_area_data = pd.read_csv(filepath_or_buffer='fw.area',delimiter='\t',index_col=False)

In [231]:
all_area_data.head(5)
series_area_df = pd.merge(all_series_data, all_area_data, on='area_code')
ser_area_industry = pd.merge(series_area_df, all_industry_data, on='industry_code')
ser_area_industry.columns
ser_area_industry_case = pd.merge(ser_area_industry, all_case_data, on='case_code')
ser_area_industry_case_cat = pd.merge(ser_area_industry_case, all_category2_data, on='category_code')
ser_area_industry_case_cat_all =  pd.merge(ser_area_industry_case_cat, all_data, on='series_id')
#ser_area_industry_occupation = pd.merge(ser_area_industry_case, all_occupation_data, on='occupation_code')

In [232]:
#ser_area_industry_occupation.columns
#ser_area_industry_case[ser_area_industry_case.case_code=='T'].head(5)
#ser_area_industry_case_cat[['area_text','category_text']].head(5)
ser_area_industry_case_cat_all.columns

Index([u'series_id', u'seasonal', u'category_code', u'datatype_code',
       u'case_code', u'industry_code', u'event_code', u'source_code',
       u'occupation_code', u'area_code', u'footnote_codes_x', u'begin_year',
       u'begin_period', u'end_year', u'end_period', u'area_text',
       u'display_level_x', u'selectable_x', u'sort_sequence_x',
       u'industry_text', u'display_level_y', u'selectable_y',
       u'sort_sequence_y', u'case_text', u'category_text', u'year', u'period',
       u'value', u'footnote_codes_y'],
      dtype='object')

In [311]:
ser_area_industry_case_cat_all[['series_id','industry_text','occupation_code','area_text','category_code','case_text',
                        'value']].head(5)

ser_area_industry_case_cat_all[['series_id','industry_text','occupation_code','area_text','category_code','case_text',
                        'value']][ser_area_industry_case_cat_all.industry_text !='All workers']


ser_area_industry_case_cat_all[['series_id','industry_text','occupation_code','area_text','category_code','case_text',
                        'value']][ser_area_industry_case_cat_all.industry_text =='Crop production'][ser_area_industry_case_cat_all.year==2012]

ser_area_industry_case_cat_all[ser_area_industry_case_cat_all.series_id == 'FWU50X111XXX81S69']

ser_area_industry_case_cat_all['series_id'] = ser_area_industry_case_cat_all['series_id'] .str.strip()

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

In [256]:
#ser_area_industry_case_cat_all[ser_area_industry_case_cat_all.series_id == 'FWU50X111XXX81S69']['year']
ser_area_industry_case_cat_all[['series_id','industry_text','area_text','category_text','case_text','year',
                        'value']][ser_area_industry_case_cat_all.industry_text =='Crop production'][ser_area_industry_case_cat_all.year== 2012]

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  app.launch_new_instance()

,series_id,industry_text,area_text,category_text,case_text,year,value
271,FWU00X111XXX80M70,Crop production,"Atlanta-Sandy Springs-Roswell, GA",Total fatalities,Fatalities in all sectors,2012,1
272,FWU00X111XXX80M72,Crop production,"Boston-Cambridge-Newton, MA-NH",Total fatalities,Fatalities in all sectors,2012,1
279,FWU00X111XXX80M84,Crop production,"Philadelphia-Camden-Wilmington, PA-NJ-DE-MD",Total fatalities,Fatalities in all sectors,2012,2
283,FWU00X111XXX80N00,Crop production,All U.S.,Total fatalities,Fatalities in all sectors,2012,224
287,FWU00X111XXX80S05,Crop production,Arkansas,Total fatalities,Fatalities in all sectors,2012,3
290,FWU00X111XXX80S06,Crop production,California,Total fatalities,Fatalities in all sectors,2012,10
299,FWU00X111XXX80S13,Crop production,Georgia,Total fatalities,Fatalities in all sectors,2012,3
305,FWU00X111XXX80S17,Crop production,Illinois,Total fatalities,Fatalities in all sectors,2012,9
309,FWU00X111XXX80S18,Crop production,Indiana,Total fatalities,Fatalities in all sectors,2012,13
313,FWU00X111XXX80S19,Crop production,Iowa,Total fatalities,Fatalities in all sectors,2012,27
317,FWU00X111XXX80S20,Crop production,Kansas,Total fatalities,Fatalities in all sectors,2012,6
321,FWU00X111XXX80S21,Crop production,Kentucky,Total fatalities,Fatalities in all sectors,2012,10
325,FWU00X111XXX80S22,Crop production,Louisiana,Total fatalities,Fatalities in all sectors,2012,1
329,FWU00X111XXX80S23,Crop production,Maine,Total fatalities,Fatalities in all sectors,2012,2
330,FWU00X111XXX80S24,Crop production,Maryland,Total fatalities,Fatalities in all sectors,2012,1
332,FWU00X111XXX80S25,Crop production,Massachusetts,Total fatalities,Fatalities in all sectors,2012,2
335,FWU00X111XXX80S26,Crop production,Michigan,Total fatalities,Fatalities in all sectors,2012,10
339,FWU00X111XXX80S27,Crop production,Minnesota,Total fatalities,Fatalities in all sectors,2012,16
343,FWU00X111XXX80S29,Crop production,Missouri,Total fatalities,Fatalities in all sectors,2012,8
347,FWU00X111XXX80S31,Crop production,Nebraska,Total fatalities,Fatalities in all sectors,2012,5
352,FWU00X111XXX80S34,Crop production,New Jersey,Total fatalities,Fatalities in all sectors,2012,1
353,FWU00X111XXX80S36,Crop production,New York State (except NYC),Total fatalities,Fatalities in all sectors,2012,7
357,FWU00X111XXX80S37,Crop production,North Carolina,Total fatalities,Fatalities in all sectors,2012,11
361,FWU00X111XXX80S38,Crop production,North Dakota,Total fatalities,Fatalities in all sectors,2012,6
365,FWU00X111XXX80S39,Crop production,Ohio,Total fatalities,Fatalities in all sectors,2012,13
372,FWU00X111XXX80S42,Crop production,Pennsylvania,Total fatalities,Fatalities in all sectors,2012,6
376,FWU00X111XXX80S45,Crop production,South Carolina,Total fatalities,Fatalities in all sectors,2012,4
378,FWU00X111XXX80S46,Crop production,South Dakota,Total fatalities,Fatalities in all sectors,2012,5
382,FWU00X111XXX80S47,Crop production,Tennessee,Total fatalities,Fatalities in all sectors,2012,4
385,FWU00X111XXX80S48,Crop production,Texas,Total fatalities,Fatalities in all sectors,2012,3
...,...,...,...,...,...,...,...
2018155,FWU50X111XXX81S05,Crop production,Arkansas,Ownership-- Private industry,Fatalities by detailed private industry,2012,3
2018158,FWU50X111XXX81S06,Crop production,California,Ownership-- Private industry,Fatalities by detailed private industry,2012,10
2018167,FWU50X111XXX81S13,Crop production,Georgia,Ownership-- Private industry,Fatalities by detailed private industry,2012,3
2018173,FWU50X111XXX81S17,Crop production,Illinois,Ownership-- Private industry,Fatalities by detailed private industry,2012,9
2018177,FWU50X111XXX81S18,Crop production,Indiana,Ownership-- Private industry,Fatalities by detailed private industry,2012,13
2018181,FWU50X111XXX81S19,Crop production,Iowa,Ownership-- Private industry,Fatalities by detailed private industry,2012,27
2018185,FWU50X111XXX81S20,Crop production,Kansas,Ownership-- Private industry,Fatalities by detailed private industry,2012,6
2018189,FWU50X111XXX81S21,Crop production,Kentucky,Ownership-- Private industry,Fatalities by detailed private industry,2012,10
2018193,FWU50X111XXX81S22,Crop production,Louisiana,Ownership-- Private industry,Fatalities by detailed private industry,2012,1
2018197,FWU50X111XXX81S23,Crop production,Maine,Ownership-- Private industry,Fatalities by detailed private industry,2012,2
2018198,FWU50X111XXX81S24,Crop production,Maryland,Ownership-- Private industry,Fatalities by detailed private industry,2012,1
2018200,FWU50X111XXX81S25,Crop production,Massachusetts,Ownership-- Private industry,Fatalities by detailed private industry,2012,2
2018203,FWU50X111XXX81S26,Crop production,Michigan,Ownership-- Private industry,Fatalities by detailed private industry,2012,10
2018207,FWU50X111XXX81S27,Crop production,Minnesota,Ownership-- Private industry,Fatalities by detailed private industry,2012,16
2018211,FWU50X111XXX81S29,Crop production,Missouri,Ownership-- Private industry,Fatalities by detailed private industry,2012,8
2018215,FWU50X111XXX81S31,Crop production,Nebraska,Ownership-- Private industry,Fatalities by detailed private industry,2012,5
2018220,FWU50X111XXX81S34,Crop production,New Jersey,Ownership-- Private industry,Fatalities by detailed private industry,2012,1
2018221,FWU50X111XXX81S36,Crop production,New York State (except NYC),Ownership-- Private industry,Fatalities by detailed private industry,2012,7
2018225,FWU50X111XXX81S37,Crop production,North Carolina,Ownership-- Private industry,Fatalities by detailed private industry,2012,11
2018229,FWU50X111XXX81S38,Crop production,North Dakota,Ownership-- Private industry,Fatalities by detailed private industry,2012,6
2018233,FWU50X111XXX81S39,Crop production,Ohio,Ownership-- Private industry,Fatalities by detailed private industry,2012,13
2018240,FWU50X111XXX81S42,Crop production,Pennsylvania,Ownership-- Private industry,Fatalities by detailed private industry,2012,6
2018244,FWU50X111XXX81S45,Crop production,South Carolina,Ownership-- Private industry,Fatalities by detailed private industry,2012,4
2018246,FWU50X111XXX81S46,Crop production,South Dakota,Ownership-- Private industry,Fatalities by detailed private industry,2012,5
2018250,FWU50X111XXX81S47,Crop production,Tennessee,Ownership-- Private industry,Fatalities by detailed private industry,2012,4
2018253,FWU50X111XXX81S48,Crop production,Texas,Ownership-- Private industry,Fatalities by detailed private industry,2012,3
2018257,FWU50X111XXX81S51,Crop production,Virginia,Ownership-- Private industry,Fatalities by detailed private industry,2012,8
2018259,FWU50X111XXX81S53,Crop production,Washington,Ownership-- Private industry,Fatalities by detailed private industry,2012,5
2018263,FWU50X111XXX81S55,Crop production,Wisconsin,Ownership-- Private industry,Fatalities by detailed private industry,2012,13
2018268,FWU50X111XXX81S69,Crop production,New York State and New York City,Ownership-- Private industry,Fatalities by detailed private industry,2012,7

In [308]:
#ser_area_industry_case_cat_all[ser_area_industry_case_cat_all.series_id == 'FWU50X111XXX81S69']['year']
ser_area_industry_case_cat_all[['series_id','industry_text','area_text','category_text','case_text','year',
                        'value']][ser_area_industry_case_cat_all.area_text =='All U.S.'][ser_area_industry_case_cat_all.year== 2012]

#ser_area_industry_case_cat_all[ser_area_industry_case_cat_all.series_id == 'FWU50X111XXX81S69']['year']
ser_area_industry_case_cat_all[['series_id','industry_text','area_text','category_text','case_text','year',
                        'value']][ser_area_industry_case_cat_all.area_text =='All U.S.'][ser_area_industry_case_cat_all.industry_text== 'All workers']

ser_area_industry_case_cat_all[['industry_text','area_text','category_text','year',
                        'value']][ser_area_industry_case_cat_all.area_text =='All U.S.'][ser_area_industry_case_cat_all.industry_text=='All workers'][ser_area_industry_case_cat_all.case_text== 'Fatalities in all sectors'][ser_area_industry_case_cat_all.category_text.str.contains('Time of incident')].sort_values(by=['year','value'])


#ser_area_industry_case_cat_all[['year','value']][ser_area_industry_case_cat_all.area_text =='All U.S.'][ser_area_industry_case_cat_all.industry_text== 'All workers']

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  app.launch_new_instance()
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:10: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,industry_text,area_text,category_text,year,value
433336,All workers,All U.S.,Time of incident-- 12:00 midnight - 3:59 a.m.,2011,295
519503,All workers,All U.S.,Time of incident-- 8:00 p.m. - 11:59 p.m.,2011,381
442083,All workers,All U.S.,Time of incident-- 4:00 a.m. - 7:59 a.m.,2011,472
502737,All workers,All U.S.,Time of incident-- 4:00 p.m. - 7:59 p.m.,2011,722
478459,All workers,All U.S.,Time of incident-- 12:00 noon - 3:59 p.m.,2011,1216
454188,All workers,All U.S.,Time of incident-- 8:00 a.m. - 11:59 a.m.,2011,1220
433337,All workers,All U.S.,Time of incident-- 12:00 midnight - 3:59 a.m.,2012,326
519504,All workers,All U.S.,Time of incident-- 8:00 p.m. - 11:59 p.m.,2012,356
442084,All workers,All U.S.,Time of incident-- 4:00 a.m. - 7:59 a.m.,2012,476
502738,All workers,All U.S.,Time of incident-- 4:00 p.m. - 7:59 p.m.,2012,647
454189,All workers,All U.S.,Time of incident-- 8:00 a.m. - 11:59 a.m.,2012,1144
478460,All workers,All U.S.,Time of incident-- 12:00 noon - 3:59 p.m.,2012,1160
433338,All workers,All U.S.,Time of incident-- 12:00 midnight - 3:59 a.m.,2013,273
519505,All workers,All U.S.,Time of incident-- 8:00 p.m. - 11:59 p.m.,2013,340
442085,All workers,All U.S.,Time of incident-- 4:00 a.m. - 7:59 a.m.,2013,455
502739,All workers,All U.S.,Time of incident-- 4:00 p.m. - 7:59 p.m.,2013,683
478461,All workers,All U.S.,Time of incident-- 12:00 noon - 3:59 p.m.,2013,1154
454190,All workers,All U.S.,Time of incident-- 8:00 a.m. - 11:59 a.m.,2013,1194
433339,All workers,All U.S.,Time of incident-- 12:00 midnight - 3:59 a.m.,2014,269
519506,All workers,All U.S.,Time of incident-- 8:00 p.m. - 11:59 p.m.,2014,369
442086,All workers,All U.S.,Time of incident-- 4:00 a.m. - 7:59 a.m.,2014,497
502740,All workers,All U.S.,Time of incident-- 4:00 p.m. - 7:59 p.m.,2014,700
454191,All workers,All U.S.,Time of incident-- 8:00 a.m. - 11:59 a.m.,2014,1181
478462,All workers,All U.S.,Time of incident-- 12:00 noon - 3:59 p.m.,2014,1270

In [284]:
by_occupation = pd.DataFrame(single_year_all_data[single_year_all_data.category_text.str.startswith('Occupation')][['category_text','value']].sort_values(by="value"))

In [286]:
by_occupation = by_occupation.reset_index()

In [289]:
by_occupation[['category_text','value']]

                                        category_text  value
0   Occupation-- Computer and Mathematical Occupat...      5
1                      Occupation-- Legal Occupations     14
2   Occupation-- Life, Physical, and Social Scienc...     23
3         Occupation-- Healthcare Support Occupations     23
4   Occupation-- Community and Social Services Occ...     23
5   Occupation-- Business and Financial Operations...     30
6   Occupation-- Education, Training, and Library ...     37
7   Occupation-- Architecture and Engineering Occu...     38
8   Occupation-- Food Preparation and Serving Rela...     47
9   Occupation-- Arts, Design, Entertainment, Spor...     52
10  Occupation-- Healthcare Practitioner and Techn...     55
11                  Occupation-- Military Occupations     57
12  Occupation-- Personal Care and Service Occupat...     71
13  Occupation-- Office and Administrative Support...     91
14                Occupation-- Production Occupations    222
15         Occupation-- Sales and Related Occupations    240
16  Occupation-- Professional and Related Occupati...    247
17  Occupation-- Farming, Fishing, and Forestry Oc...    261
18  Occupation-- Building and Grounds Cleaning and...    269
19        Occupation-- Protective Service Occupations    282
20  Occupation-- Sales and Office Occupations (41-...    331
21  Occupation-- Installation, Maintenance, and Re...    354
22                Occupation-- Management Occupations    467
23  Occupation-- Management, Business, and Financi...    497
24          Occupation-- Service Occupations (31--39)    692
25  Occupation-- Management, Business, Science, an...    744
26  Occupation-- Construction and Extraction Occup...    798
27  Occupation-- Transportation and Material Movin...   1233
28  Occupation-- Natural Resources, Construction, ...   1413
29  Occupation-- Production, Transportation, and M...   1455

In [225]:
all_case_data.head(5)
all_category_data.tail(5)
all_category2_data.tail(5)

    category_code                              category_text
322           Y74        Worker location-- Convenience store
323           Y75          Worker location-- Office building
324           Y76         Worker location-- Restaurant, cafe
325           Y7X          Worker location-- Public building
326           Y8X  Worker location-- Residential institution

In [205]:
series_area_df.head(5)
all_occupation_data.head(5)
#all_industry_data

,occupation_code,occupation_text,display_level,selectable,sort_sequence
0,000000,All occupations,0,T,1
1,111011,Chief executives,4,T,5
2,11101X,Chief executives,3,T,4
3,111021,General and operations managers,4,T,7
4,11102X,General and operations managers,3,T,6